/**
 * Cached Google Maps statistics
 * Generated by scripts/fetch-google-maps-stats.js
 * Last updated: 2025-10-02T06:19:33.465Z
 */

import type { GoogleMapsStats } from './googleMaps.js';

export const cachedGoogleMapsStats: Record<string, GoogleMapsStats> = {
  '100234331600740025841': {
    userId: '100234331600740025841',
    totalPoints: 48836,
    totalViews: 0,
    totalPhotos: 8795,
    totalReviews: 242,
    lastUpdated: new Date('2025-10-02T06:19:33.464Z')
  }
};

export function getCachedStats(userId: string): GoogleMapsStats | null {
  return cachedGoogleMapsStats[userId] || null;
}
