/**
 * Cached Google Maps statistics
 * Generated by scripts/fetch-google-maps-stats.js
 * Last updated: 2026-01-19T06:28:10.358Z
 */

import type { GoogleMapsStats } from './googleMaps.js';

export const cachedGoogleMapsStats: Record<string, GoogleMapsStats> = {
  '100234331600740025841': {
    userId: '100234331600740025841',
    totalPoints: 49066,
    totalViews: 0,
    totalPhotos: 0,
    totalReviews: 0,
    lastUpdated: new Date('2026-01-19T06:28:10.357Z')
  }
};

export function getCachedStats(userId: string): GoogleMapsStats | null {
  return cachedGoogleMapsStats[userId] || null;
}
